name: Aegis MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest pandas scikit-learn==1.6.1 fastapi xgboost

      - name: Run Pytest
        run: pytest backend/tests/

  mlops_gate:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install MLOps Dependencies
        run: pip install evidently==0.4.33 mlflow==2.14.3 supabase==2.5.1 pandas scikit-learn==1.6.1
        
      - name: Run Data Drift Monitor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python backend/drift_monitor.py
        
      - name: Run MLflow Performance Gate
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/engrmaziz/heart-disease-platform.mlflow
          MLFLOW_TRACKING_USERNAME: engrmaziz
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: python backend/mlflow_tracker.py

  deploy_backend:
    runs-on: ubuntu-latest
    needs: mlops_gate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "huggingface_hub[cli]"
          hf upload EngrAhmedRehan/aegis-heart-disease-api ./backend / --repo-type space --token $HF_TOKEN
  
  deploy_frontend:
    runs-on: ubuntu-latest
    needs: mlops_gate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./frontend